### ISSUE TITLE
Wordpress fails if other plugins are using Mixpanel

### ISSUE THREAD

**Issue by Geesu** [davidhme/easy-pricing-tables-free#1]
Ran into this problem as a plugin I'm working on uses Mixpanel as well, but it is using `require_once`.

Any chance you could change this https://github.com/davidhme/easy-pricing-tables-free/blob/master/includes/analytics.php#L4 so other users won't run into a conflict of the class being defied twice?

**Comment by davidhme** [comment]
Thanks Josh, we'll fix it in the next release!

**Comment by rnovotny** [comment]
https://github.com/davidhme/easy-pricing-tables-free/commit/66207d03e78776561c8f39c0dd7dde85d348ccd1

Will only include mixpanel if the class doesn't already exist.  Will be part of 2.2.0
